### ISSUE TITLE
improper accuracy calculation

### ISSUE THREAD

**Issue by rturiano** [datatrigger/nlp_hugging_face#2]
see https://github.com/datatrigger/nlp_hugging_face/pull/1

**Comment by datatrigger** [comment]
Hello, again thank you very much for pointing out this mistake. I find it very confusing to set the actual labels as an attribute of the result of `trainer.predict()`, and name them just `label_ids`. [This tutorial](https://huggingface.co/course/chapter3/3?fw=pt) helped me clarify the exact status of the different attributes of the `predictions` object.

I corrected the notebook, the accuracy went down to 98.65%.

Best regards,
Vincent
